server:
  port: 8080
  servlet:
    session:
      tracking-modes: cookie

spring:
  profiles:
    active: "dev"
  data:
    web:
      pageable:
        default-page-size: 20
        one-indexed-parameters: true
        page-parameter: page

security:
  jwt:
    token:
      secret-key: thisIsASecretKeyString
      expired-second: 604800  # 7 days
      refresh-second: 1209600 # 14 days
