server:
  port: 8080
  servlet:
    session:
      tracking-modes: cookie

spring:
  profiles:
    active: "dev"

security:
  jwt:
    token:
      secret-key: thisIsASecretKeyString
      expired-second: 604800  # 7 days
      refresh-second: 1209600 # 14 days
