spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./scode.h2;MODE=MySQL; # filename: scode.h2.mv.db
    username: sa
    password: ""
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
